name       : iio-sensor-proxy
version    : '3.4'
release    : 4
source     :
    - https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/archive/3.4/iio-sensor-proxy-3.4.tar.gz : 9339af3bc83994a43ab25231a8ffe9ada6d9afbc16edc44d575dd9f2a69ede3c
license    : GPL-3.0-only
component  : desktop.util
summary    : IIO sensors (ambient light, compass, orientation) to D-Bus proxy
description: |
    IIO sensors (ambient light, compass, orientation) to D-Bus proxy
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
setup      : |
    %meson_configure --sysconfdir=/usr/share
build      : |
    %ninja_build
install    : |
    %ninja_install
