name       : iio-sensor-proxy
version    : '2.8'
release    : 3
source     :
    - https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/archive/2.8/iio-sensor-proxy-2.8.tar.gz : 3129e89777ad308400685d3da16931b404ecc4d6b0a48fe217b405e3310a8373
license    : GPL-3.0
component  : desktop.util
summary    : IIO sensors (ambient light, compass, orientation) to D-Bus proxy
description: |
    IIO sensors (ambient light, compass, orientation) to D-Bus proxy
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - autoconf-archive
setup      : |
    %autogen --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
