name       : iio-sensor-proxy
version    : '2.4'
release    : 2
source     :
    - https://github.com/hadess/iio-sensor-proxy/archive/2.4.tar.gz : 73c03e3deba1d1460db90d9d25593591c0691b38e9138afdbcad7f5443c244cd
license    : GPL-3.0
component  : desktop.util
summary    : IIO sensors (ambient light, compass, orientation) to D-Bus proxy
description: |
    IIO sensors (ambient light, compass, orientation) to D-Bus proxy
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - autoconf-archive
setup      : |
    %autogen --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
