name       : iio-sensor-proxy
version    : 1.3
release    : 1
source     :
    - https://github.com/hadess/iio-sensor-proxy/archive/1.3.tar.gz : 736e831dec40640a6e2cd0f17e57e82e1ef817d5d6f87b345ce2c5e6894368c5
license    : GPL-3.0
component  : desktop.util
summary    : IIO sensors (ambient light, compass, orientation) to D-Bus proxy
description: |
    IIO sensors (ambient light, compass, orientation) to D-Bus proxy
builddeps  :
    - pkgconfig(gtk-doc)
    - autoconf-archive
setup      : |
    %autogen --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
